---
- name: ===> Install chrony
  yum:
    name: chrony
    state: present

- name: ===> Start chronyd
  service:
    name: chronyd
    state: started
    enabled: True

- name: ===> Execute time synchronization
  command: chronyc sources
