---
- name: ===> Yum Env Packages
  yum:
    name: ['yum-utils', 'device-mapper-persistent-data', 'lvm2']
    state: present

- name: ===> Add docker-ce repository
  command: yum-config-manager --add-repo https://mirrors.aliyun.com/docker-ce/linux/centos/docker-ce.repo

- name: ===> Install container.io
  yum:
    name: containerd.io
    state: present

- name: ===> Create /etc/containerd
  file:
    path: /etc/containerd
    state: directory
    mode: '0755'

- name: ===> Copy config.toml
  copy:
    src: config.toml
    dest: /etc/containerd/config.toml
    owner: root
    group: root
    mode: '0644'

- name: ==> Start containerd
  service:
    name: containerd
    state: started
    enabled: yes

- name: ===> Validate ctr
  command: ctr version 
  register: ctrRes

- name: ===> Stdout ctrRes
  debug: msg={{ ctrRes.stdout_lines }}

- name: Extract cri-tools tar.gz to /usr/local/bin
  unarchive:
    src: crictl-v1.22.0-linux-amd64.tar.gz
    dest: /usr/local/bin

- name: Validate Crictl
  command: crictl version
  register: crictlRes

- name: Stdout crictlRes
  debug: msg={{ crictlRes.stdout_lines }}

