---
- name: ===> Disable swap
  command: swapoff -a

- name: ===> K8s Kernel Conf
  blockinfile:
    path: /etc/sysctl.d/k8s.conf
    block: |
      net.ipv4.ip_forward = 1
      vm.swappiness = 0
      net.bridge.bridge-nf-call-ip6tables = 1
      net.bridge.bridge-nf-call-iptables = 1
      fs.may_detach_mounts = 1
    state: present
    create: yes

- name: ===> Execute sysctl
  shell: sysctl -p /etc/sysctl.d/k8s.conf 
  register: sysctlRes
  ignore_errors: yes

- name: ===> Output sysctlRes
  debug: msg={{ sysctlRes.stdout_lines }}

- name: ===> Ipvs Modules Conf
  blockinfile:
    path: /etc/sysconfig/modules/ipvs.modules
    block: |
      #!/bin/bash
      modprobe -- br_netfilter
      modprobe -- ip_vs
      modprobe -- ip_vs_rr
      modprobe -- ip_vs_wrr
      modprobe -- ip_vs_sh
      modprobe -- nf_conntrack_ipv4
    state: present
    mode: '0755'
    create: yes

- name: ===> Bash ipvs.modules
  command: bash /etc/sysconfig/modules/ipvs.modules

- name: ===> Validate ipvs.modules
  shell: lsmod | grep -E "ip_vs|nf_conntrack_ipv4"
  register: ipvsRes

#- name: ===> Stdout ipvsRes
#  debug: var=ipvsRes.stdout_lines
#  with_items: ipvsRes.results

- name: ===> Stdout ipvsRes
  debug: msg={{ ipvsRes.stdout_lines }}

