---
- name: ===> Add kubernetes.repo
  copy:
    src: kubernetes.repo
    dest: /etc/yum.repos.d/kubernetes.repo
    owner: root
    group: root
    mode: '0644'
   
- name: ===> Validate repo
  shell: yum list kubeadm --showduplicates -y | grep 1.22.0
  args:
    warn: false
  register: kubeRes

- name: ===> Stdout kubRes
  debug: msg={{ kubeRes.stdout_lines }}

- name: ===> Install kubelet/kubeadm/kubectl
  yum:
    name: ['kubelet-1.22.0', 'kubeadm-1.22.0', 'kubectl-1.22.0' ]
    state: present

- name: ===> Enable kubelet
  service:
    name: kubelet
    state: started
    enabled: yes

